#! /bin/bash --login

set -e

ORG=$1
NAME=$2

WORK_DIR=/tmp/$ORG/$NAME

INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Starting to build docs for $ORG/$NAME. Work Dir is $WORK_DIR"

#rm -fr $WORK_DIR
mkdir -p $WORK_DIR

cd $WORK_DIR

echo "Cloning $ORG/$NAME"

#git clone --depth=1 git@github.com:$ORG/$NAME .

echo "Copying jekyll files"

cp -rv $INSTALL_DIR/jekyll/* docs/.

cd docs

echo "Carregando RVM"
source ~/.rvm/scripts/rvm

rvm use 2.1.2
bundle install
jekyll build --config _config.yml,_site.yml

echo "Deploying!"
#s3-jekyll-deploy projetos.vidageek.net
